In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
def f(i):
    return (2 ** (i + 1)) / (i + 1)

In [3]:
np.fromfunction(f, (20,))

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [4]:
def sum(i):
    return 0.1 ** (3 * i) * 0.2 ** (4 * i)

In [5]:
np.fromfunction(sum, (6,)).sum()

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [6]:
a = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [7]:
X = np.random.random((5, 2))

x, y = X[:,0], X[:,1]
ro = np.hypot(x, y)
fi = np.arctan2(y, x)
print(ro)
print(fi)

[0.96843909 0.86096954 1.11444926 1.28923401 1.06732775]
[0.91975714 1.4530704  0.90281427 0.69624044 0.59603607]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [8]:
X = np.random.random((10, 10))

print((np.argmax(X) // 10, np.argmax(X) % 10))
#выделить строчку и столбец

(7, 3)


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [9]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

q = np.subtract.outer(X[:,0], y[:,0])
w = np.subtract.outer(X[:,1], y[:,1])
np.argmin(np.hypot(q, w))

6

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [10]:
def f(i):
    if i < 0:
        return i ** 2 + 2 * i + 6
    elif i > 2 and i >= 0:
        return i ** 2 + 4 * i - 4
    else:
        return i + 6

In [11]:
otr = np.arange(-3, 4)

In [12]:
np.array(list(map(f, otr)))

array([ 9,  6,  5,  6,  7,  8, 17])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [13]:
X = np.random.random((10, 10))
X

array([[0.40446696, 0.87170758, 0.37529253, 0.29938438, 0.99595508,
        0.20018038, 0.10169523, 0.62957051, 0.97126364, 0.45780559],
       [0.55517958, 0.02724333, 0.06420196, 0.10389902, 0.00840012,
        0.83934484, 0.42412573, 0.97334132, 0.08535147, 0.88644183],
       [0.70289508, 0.70147349, 0.31923856, 0.35061384, 0.51277269,
        0.51647911, 0.96723846, 0.39041575, 0.42870703, 0.86346171],
       [0.3896933 , 0.00191066, 0.7165535 , 0.76182222, 0.11746222,
        0.2512287 , 0.24189488, 0.26479837, 0.12956834, 0.55477175],
       [0.36317061, 0.85558958, 0.15374707, 0.62470823, 0.96464878,
        0.91713368, 0.41509785, 0.05331122, 0.5354841 , 0.15918947],
       [0.53128966, 0.79449059, 0.56989716, 0.68783959, 0.87275622,
        0.38278219, 0.2560584 , 0.70389473, 0.20253512, 0.02741963],
       [0.46776509, 0.36933252, 0.39777137, 0.39039397, 0.08613429,
        0.20926605, 0.24798114, 0.27034975, 0.27988546, 0.60415848],
       [0.356134  , 0.10411638, 0.0537520

In [14]:
X - np.mean(X, axis=1).reshape(10, 1)

array([[-0.12626523,  0.3409754 , -0.15543965, -0.23134781,  0.46522289,
        -0.33055181, -0.42903696,  0.09883832,  0.44053146, -0.0729266 ],
       [ 0.15842666, -0.36950959, -0.33255096, -0.2928539 , -0.3883528 ,
         0.44259192,  0.02737281,  0.5765884 , -0.31140145,  0.48968891],
       [ 0.12756551,  0.12614392, -0.25609101, -0.22471573, -0.06255688,
        -0.05885046,  0.39190889, -0.18491382, -0.14662254,  0.28813213],
       [ 0.04672291, -0.34105974,  0.3735831 ,  0.41885182, -0.22550817,
        -0.09174169, -0.10107551, -0.07817203, -0.21340206,  0.21180136],
       [-0.14103745,  0.35138152, -0.35046099,  0.12050017,  0.46044072,
         0.41292562, -0.08911021, -0.45089684,  0.03127604, -0.34501859],
       [ 0.02839333,  0.29159426,  0.06700083,  0.18494326,  0.36985989,
        -0.12011414, -0.24683793,  0.2009984 , -0.30036121, -0.4754767 ],
       [ 0.13546128,  0.03702871,  0.06546756,  0.05809016, -0.24616952,
        -0.12303776, -0.08432267, -0.06195406

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [15]:
X = np.random.normal(loc=5, scale=2., size=1000)

In [16]:
np.mean(X), np.var(X)

(5.059592434282345, 4.0407838871157615)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [17]:
#сначала прибавлю ко всей матрице вектор-строчку[0..4], потом вектор-столбец[0..4] и все по модулю 5
a = np.zeros((5,5))
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [18]:
a += np.arange(5).reshape((5, 1))
a = a % 5
a

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])